-- MySQL Script generated by MySQL Workbench
-- Fri Oct 10 00:13:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema club_del_mate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema club_del_mate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `club_del_mate2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `club_del_mate2` ;

-- -----------------------------------------------------
-- Table `club_del_mate`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_del_mate`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `club_del_mate`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_del_mate`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `club_del_mate`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_del_mate`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(256) NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `rol_id` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `club_del_mate`.`rol` (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `club_del_mate`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_del_mate`.`direccion` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(50) NOT NULL,
  `numero` INT NOT NULL,
  `localidad` VARCHAR(50) NOT NULL,
  `provincia` VARCHAR(50) NOT NULL,
  `codigo_postal` VARCHAR(10) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id_direccion`),
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `direccion_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `club_del_mate`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `club_del_mate`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_del_mate`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATE NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `pedido_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `club_del_mate`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `club_del_mate`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_del_mate`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id_producto`, `usuario_id`),
  INDEX `categoria_id` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_producto_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `club_del_mate`.`categoria` (`id_categoria`),
  CONSTRAINT `fk_producto_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `club_del_mate`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `club_del_mate`.`pedido_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_del_mate`.`pedido_producto` (
  `id_pedido` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_producto`),
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `pedido_producto_ibfk_1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `club_del_mate`.`pedido` (`id_pedido`),
  CONSTRAINT `pedido_producto_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `club_del_mate`.`producto` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
